# https://taskfile.dev

version: '3'
vars:
  ARTIFACT_DIRECTORY: ./artifacts
  LOCAL_DIRECTORY: "{{ .HOME }}/git/sheldonhull/sheldonhull.hugo/content/posts/2021"
tasks:
  default:
    cmds:
      - task --list
    silent: true
  init:
    desc: initialize project tooling and directories
    cmds:
      - |
        mkdir -p {{ .ARTIFACT_DIRECTORY }}
        chmod -R a+rwx ./artifacts
        go mod tidy
  build:
    desc: build app
    cmds:
      - |
        rm ./artifacts/sharedbrain
        go build -o ./artifacts/sharedbrain
  test:
    desc: run go tests
    cmds:
      - task: build
      - |
        go test -v ./backlinker
  coverage:
    desc: add code coverage metrics
    cmds:
      - |
        go install github.com/jpoles1/gopherbadger@master
        go test ./backlinker/ -coverprofile ./artifacts/cover.out
        go tool cover -html=./artifacts/cover.out -o ./artifacts/coverage.html
        gopherbadger -md="README.md,coverage.md" -tags 'unit' # -manualcov=95
  localrun:
      desc: run tool locally against specific blog directory
      cmds:
        - task: build
        - |
          {{ .ARTIFACT_DIRECTORY }}/sharedbrain  -content {{ .LOCAL_DIRECTORY }} -dest {{ .LOCAL_DIRECTORY }}
